
name: ChukcleWorker

hotpatch:
  #- https://raw.githubusercontent.com/ChenYFan/ClientWorker/gh-pages/cw.js
  - https://cdn.jsdelivr.net/gh/ChenYFan/ClientWorker/cw.js

hotpatch:
  #- https://raw.githubusercontent.com/ChenYFan/ClientWorker/gh-pages/config.yaml
  - https://cdn.jsdelivr.net/gh/ChenYFan/ClientWorker/config.yaml

catch_rules:

  - rule: _
    transform_rules:
      - search: \#.+
        searchin: url
        replace: ''
      - search: _ 
        action: fetch
        fetch:
          engine: fetch 
      - search: (^4|^5) 
        searchin: status 
        action: return
        return:
          body: The GateWay is down!This Page is provided by ClientWorker!
          status: 503

  # - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/npm|unpkg\.com)
  #   transform_rules:
  #     - search: _
  #       replace:
  #         - _
  #         - https://unpkg.zhimg.com
  #         - https://npm.elemecdn.com
  #         - https://code.bdstatic.com/npm
  #         #- https://npm.sourcegcdn.com
  #         #- https://cdn.bilicdn.tk/npm
  #       fetch:
  #         status: 200
  #         engine: parallel
  #         preflight: false

  # - rule: ^https\:\/\/cdnjs\.cloudflare\.com\/ajax\/libs
  #   transform_rules:
  #     - search: _
  #       replace:
  #         - _
  #         - https://cdn.bootcdn.net/ajax/libs
  #         - https://lib.baomitu.com
  #         - https://mirrors.cqupt.edu.cn/cdnjs/ajax/libs
  #         - https://cdn.staticfile.org
  #         - https://mirrors.sustech.edu.cn/cdnjs/ajax/libs
  #         #- https://cdnjs.sourcegcdn.com/ajax/libs
  #       action: fetch
  #       fetch:
  #         status: 200
  #         engine: parallel
  #         preflight: false

  # - rule: (?<=^https\:\/\/s2.loli/(.*))\.jpg$
  #   transform_rules:
  #     - search: image\/webp
  #       searchin: header
  #       searchkey: Accept
  #       replace: .webp
  #       replacein: url
  #       replacekey: .jpg

  # - rule: (?<=^https\:\/\/s2.loli/(.*))\.png$
  #   transform_rules:
  #     - search: image\/webp
  #       searchin: header
  #       searchkey: Accept
  #       replace: .webp
  #       replacein: url
  #       replacekey: .jpg

  # - rule: (?<=^https\:\/\/s2.loli/(.*))\.gif$
  #   transform_rules:
  #     - search: image\/webp
  #       searchin: header
  #       searchkey: Accept
  #       replace: .webp
  #       replacein: url
  #       replacekey: .jpg